name: amrex-bittree

on:
  push:
    branches: 
      - development
    paths-ignore:
      - '**.rst'
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

jobs:
  setup-submit:
    name: "setup-submit" 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: Install Dependencies
      run: |
          sudo apt-get update -y && apt-get install -y apt-utils && apt-get upgrade -y
          sudo apt-get install -y libhdf5-openmpi-dev openmpi-bin
          sudo apt-get install -y python3 python3-dev python3-pip
          sudo apt-get install -y python-is-python3
          sudo apt-get install git-all
    - name: Install Jobrunner
      run: |
          python3 setup.py develop --user
          export PATH=$PATH:$HOME/.local/bin
    - name: Clone External Repo
      run: |
          gh repo clone Lab-Notebooks/AMReX-Bittree-Performance
    - name: Setup Bittree
      run: |
          cd AMReX-Bittree-Performance
          ./configure --help
