name: SimpleProject

on:
  push:
    branches: 
      - development
    paths-ignore:
      - '**.rst'
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

jobs:
  setup_submit:
    name: "setup-submit" 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: Install jobrunner
      run: |
          sudo apt-get update -y && apt-get install -y apt-utils && apt-get upgrade -y
          sudo apt-get install -y python3 python3-dev python3-pip
          sudo apt-get install -y python-is-python3
          python3 setup.py develop --user
          export PATH=$PATH:$HOME/.local/bin
    - name: Run jobrunner tests
      run: |
          cd tests/SimpleProject
          jobrunner setup JobObject
          jobrunner submit JobOject
    - name: Verify output
      run: |
          cd tests/SimpleProject/JobObject
          diff job.setup setupSolution.sh
          diff job.submit submitSolution.sh
          diff job.output submitOutput.txt
