name: simple-project

on:
  push:
    branches: 
      - development
    paths-ignore:
      - '**.rst'
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

jobs:
  setup-submit:
    name: "setup-submit" 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: Install Jobrunner and Dependencies
      run: |
          sudo apt-get update -y && apt-get install -y apt-utils && apt-get upgrade -y
          sudo apt-get install -y python3 python3-dev python3-pip
          sudo apt-get install -y python-is-python3
          python3 setup.py develop --user
          export PATH=$PATH:$HOME/.local/bin
    - name: Run Tests
      run: |
          cd tests/Simple-Project
          jobrunner setup JobObject
          jobrunner submit JobObject
    - name: Verify Output
      run: |
          cd tests/Simple-Project/JobObject
          diff job.setup setupSolution.sh
          diff job.submit submitSolution.sh
          cat job.output
          #diff job.output submitOutput.txt
